name: 'generate-types'
on:
  push:
    branches:
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - run: supabase init
      - run: supabase db start
      - name: Generate TypeScript types
        run: supabase gen types typescript --project-id "eftqpoetlueihfnlckbp" --schema public > src/lib/supabase-types.ts
